// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWx50XQpSTzjDALU79qrjynoM_CvIfcTk',
    appId: '1:906301605644:web:58fa8bdc578a01a63feb29',
    messagingSenderId: '906301605644',
    projectId: 'myvideodownloading',
    authDomain: 'myvideodownloading.firebaseapp.com',
    storageBucket: 'myvideodownloading.appspot.com',
    measurementId: 'G-JKGHBFYQDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqumUZJrfmlGVYKfcyOuWbb9YwGhzL9y4',
    appId: '1:906301605644:android:81adb1737cb28ccb3feb29',
    messagingSenderId: '906301605644',
    projectId: 'myvideodownloading',
    storageBucket: 'myvideodownloading.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3oXdY9z20MrIvyqJL7EFMgkQAbH_xf0',
    appId: '1:906301605644:ios:d8d343e16a4a00533feb29',
    messagingSenderId: '906301605644',
    projectId: 'myvideodownloading',
    storageBucket: 'myvideodownloading.appspot.com',
    iosBundleId: 'com.example.flutterAppEcommerce',
  );
}
